### ISSUE TITLE
Subshells in remote commands are executed in local environment

### ISSUE THREAD

**Issue by IcanDivideBy0** [neoziro/grunt-shipit#19]
```
grunt.shipit.remote('echo "`hostname`"');
```
will make the remote server echoing the local hostname, which is really disturbing
I think the command should be wrapped with single quotes [here](https://github.com/neoziro/grunt-shipit/blob/master/lib/ssh/connection.js#L59)

**Comment by neoziro** [comment]
@IcanDivideBy0 ping!

**Comment by neoziro** [comment]
@IcanDivideBy0 now part of https://github.com/neoziro/ssh-pool
