### ISSUE TITLE
gulp version

### ISSUE THREAD

**Issue by jackocnr** [neoziro/grunt-shipit#40]
Hi there,

Would you consider porting shipit to gulp? How hard do you think that would be? There don't seem to be many deploy tools for gulp whatsoever!

Cheers,
Jack

**Comment by neoziro** [comment]
@jackocnr I plan to create a standalone version of Shipit and some plugin for grunt and gulp. I should start to do that very soon.

**Comment by samuelbeek** [comment]
Did you start?

**Comment by neoziro** [comment]
@samuelbeek it's done, https://github.com/shipitjs/shipit
